appname = API_CRUD_SPY
httpport = 8081
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:posgres@127.0.0.1/SPY?sslmode=disable&search_path=public

# url Post http://localhost:8081/v1/"nombre del servicio"
# {
#     "Nombres": "ABC",
#     "Apellidos": "DEF",
#     "NumeroIdentificacionUsuarios": "123",
#     "Email": "corre@gmail.com",
#     "Telefono": 123456789,
#     "IdContrasenaFk": {
#         "Id": #
#     },
#     "Estado": true/false,
#     "IdRolesFk": {
#         "Id": #
#     },
#     "Imagen": "Codigo de la imagne en base64"
# }
# url GetAll http://localhost:8081/v1/"nombre del servicio"
# url GetOne http://localhost:8081/v1/"nombre del servicio"/"id"
# url Put http://localhost:8081/v1/"nombre del servicio"/"id"
# {
#     "Nombres": "ABC",
#     "Apellidos": "DEF",
#     "NumeroIdentificacionUsuarios": "123",
#     "Email": "corre@gmail.com",
#     "Telefono": 123456789,
#     "IdContrasenaFk": {
#         "Id": #
#     },
#     "Estado": true/false,
#     "IdRolesFk": {
#         "Id": #
#     },
#     "Imagen": "Codigo de la imagne en base64"
# }